jobs:
- job: macos
  pool:
    vmImage: 'macos-10.14'
  variables:
    TARGET: x86_64-apple-darwin
    RID: osx-x64
  steps:
  - script: |
      brew install autoconf automake libtool pkg-config openssl libusb
    displayName: Install autotools, openSSL
  - script: |
      brew install --head libplist libusbmuxd libimobiledevice
    displayName: Install libplist, libusbmuxd, libimobiledevice
  - script: |
      export PKG_CONFIG_PATH="$(brew --prefix)/opt/openssl/lib/pkgconfig:$PKG_CONFIG_PATH"
      ./autogen.sh --host=$TARGET
      make
    displayName: Build

- job: linux
  variables:
    TARGET: x86_64-unknown-linux-gnu
    RID: ubuntu.16.04-x64
    CFLAGS: -fPIC
  pool:
    vmImage: 'ubuntu-16.04'
  container:
    image: ubuntu:18.04
    options: "--name ci-container -v /usr/bin/docker:/tmp/docker:ro"
  steps:
  - script: |
      /tmp/docker exec -t -u 0 ci-container \
      sh -c "apt-get update && DEBIAN_FRONTEND=noninteractive apt-get -o Dpkg::Options::="--force-confold" -y install sudo"
    displayName: Set up sudo
  - script: |
      sudo apt-get update
      sudo apt-get upgrade -y
      sudo apt-get install -y --no-install-recommends lsb-release automake make libtool clang libssl-dev pkg-config libusb-1.0-0-dev gnupg
    displayName: Install build dependencies
  - script: |
      echo "deb http://ppa.launchpad.net/quamotion/ppa/ubuntu bionic main" | sudo tee -a  /etc/apt/sources.list.d/quamotion.list
      sudo apt-key adv --keyserver keyserver.ubuntu.com --recv E25E7A74
      sudo apt-get update
      sudo apt-get install -y --no-install-recommends libplist-dev libplist++-dev libusbmuxd-dev libimobiledevice-dev
    displayName: Install libplist, libusbmuxd, libimobiledevice
  - script: |
      ./autogen.sh --host=$TARGET
      make
    displayName: Build
