jobs:
- job: macos
  pool:
    vmImage: 'macOS-10.14'
  variables:
    TARGET: x86_64-apple-darwin
  steps:
  - script: |
      brew install autoconf automake libtool pkg-config
    displayName: Install autotools
  - script: |
      ./autogen.sh --host=$TARGET --without-cython --enable-static=no --enable-shared=yes
      make
    displayName: Build

- job: linux
  pool:
    vmImage: 'ubuntu-16.04'
  variables:
    TARGET: x86_64-unknown-linux-gnu
    CFLAGS: -fPIC
  container:
    image: ubuntu:18.04
    options: "--name ci-container -v /usr/bin/docker:/tmp/docker:ro"
  steps:
  - script: |
      /tmp/docker exec -t -u 0 ci-container \
      sh -c "apt-get update && DEBIAN_FRONTEND=noninteractive apt-get -o Dpkg::Options::="--force-confold" -y install sudo"
    displayName: Set up sudo
  - script: |
      sudo apt-get update
      sudo apt-get upgrade -y
      sudo apt-get install -y --no-install-recommends lsb-release automake make libtool clang
    displayName: Install build dependencies
  - script: |
      ./autogen.sh --host=$TARGET --without-cython --enable-static=no --enable-shared=yes
      make
    displayName: Build